import { LocationFeature, LocationFeatureCollection } from "@notthesamadamsguy/location-finder-types";

import * as locationDao from "../daos/location_dao.ts";
import { NearbyLocationsParams, ServiceReply } from "../types.ts";
import { logger } from "../logging/logger.ts";

/**
 * @typedef LocationServiceReply
 * @property {boolean} success - Whether or not the action was successful.
 * @property {string} message - An optional message returned from the action.
 * @property {LocationFeature | LocationFeatureCollection | undefined} result - The data generated by the service.
 */
export type LocationServiceReply = ServiceReply & {
  result?: LocationFeature | LocationFeatureCollection | string | undefined | null;
};

export type NearbyLocationsServiceReply = ServiceReply & {
  result?: LocationFeatureCollection;
}

/**
 * Get the location's data based on the provided ID value.
 * @param {string} locationId - a location's ID string
 * @returns {Promise<LocationServiceReply>} - a Promise, resolving to a LocationServiceReply object.
 */
export const getLocation = async (
  locationId: string
): Promise<LocationServiceReply> => {
  try {
    const location = await locationDao.findById(locationId);
    return { success: true, result: location };
  } catch (err: any) {
    throw new Error("Unable to fetch location data.", err);
  }
};

/**
 * Get data for all locations in the database.
 * @returns {Promise<LocationServiceReply>} - a Promise, resolving to a LocationServiceReply object
 */
export const getAllLocations = async (): Promise<LocationServiceReply> => {
  try {
    const locations = await locationDao.findAll();
    return { success: true, result: locations };
  } catch (err: any) {
    throw new Error("Unable to fetch locations data.", err);
  }
};

/**
 * Get locations nearby the given coordinates.
 *
 * @param {NearbyLocationsParams} - data for the location search
 * @returns {Promise<NearbyLocationsServiceReply>} - a Promise, resolving to a NearbyLocationsServiceReply object
 */

export const getNearbyLocations = async (
  params: NearbyLocationsParams
): Promise<NearbyLocationsServiceReply> => {
  const { latitude, longitude, radius, height, width, unitOfDistance, sort } =
    params;

  try {
    const data = await locationDao.findNearby({
      latitude,
      longitude,
      radius,
      height,
      width,
      unitOfDistance,
      sort,
    });
    return { success: true, result: data };
  } catch (err: any) {
    logger.error(err);
    throw new Error(`Unable to fetch nearby locations: ${err}`);
  }
};

/**
 * Add a new Location into the database.
 * @param {LocationFeature} location - data for the location
 * @returns {Promise<LocationServiceResult>} a Promise, resolving to a LocationServiceResult object.
 */
export const addLocation = async (
  location: LocationFeature
): Promise<LocationServiceReply> => {
  try {
    const locationKey = await locationDao.insert(location);
    return { success: true, result: locationKey };
  } catch (err: any) {
    logger.error(err);
    throw new Error("Unable to save location data", err);
  }
};

/**
 * Update a Location in the database.
 * @param {LocationFeature} location - data for the location
 * @returns {Promise<LocationServiceResult>} a Promise, resolving to a LocationServiceResult object.
 */
export const updateLocation = async (
  location: LocationFeature
): Promise<LocationServiceReply> => {
  try {
    const locationKey = await locationDao.update(location);
    return { success: true, result: locationKey };
  } catch (err: any) {
    logger.error(err);
    throw new Error("Unable to update location data", err);
  }
};

/**
 * Remove a Location from the database.
 * @param {string} locationId - the location's ID
 * @returns {Promise<LocationServiceResult>} a Promise, resolving to a LocationServiceResult object.
 */
export const removeLocation = async (
  locationId: string
): Promise<LocationServiceReply> => {
  try {
    const isDeleted = await locationDao.remove(locationId);
    return { success: isDeleted, result: undefined };
  } catch (err: any) {
    logger.error(err);
    throw new Error("Unable to delete location data", err);
  }
};
